sudo: required
services:
  - docker

before_install:
  - docker build -t rameshthambusamy/docker-react -f Dockerfile.dev .

script:
  - docker run rameshthambusamy/docker-react npm run test -- --coverage