sudo: required
services:
  - docker
before_install:
  - docker build -t rameshthambusamy/docker-react -f Dockerfile.dev .
scripts:
  - docker container run rameshthambusamy/docker-react npm run test -- --coverage

